---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update-cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt: 
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Add PHP-support for Apache2
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
