---

- hosts: all
  become: true
  tasks:

  - name: Remove Apache2 and PHP Package
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"


  - name: Remove httpd and PHP Packages
    dnf:
      name:
        - httpd
        - php
      state: absent
    when: ansible_distribution == "CentOS" 
