---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install Updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Net-Tools (Ubuntu)
    tags: net-tools
    apt:
      name:
        - net-tools
    when: ansible_distribution == "Ubuntu"




- hosts: workstations
  become: true
  tasks:

  - name: Install Unzip
    package:
      name: unzip

  - name: Install Terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.1.3/terraform_1.1.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
    




- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache2 and PHP for Ubuntu-Servers
    tags: ubuntu,apache2,php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache2 and PHP for CentOS-Servers
    tags: centos,apache2,php
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Copy default-HTML file to web-server
    tags: apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644








- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB Package (CentOS)
    tags: centos,mariadb,db
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install MariaDB Package (Ubuntu)
    tags: ubuntu,mariadb,db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"









- hosts: file_servers
  become: true
  tasks:

  - name: Install Samba Package
    tags: samba
    package:
      name: samba
      state: latest

